"""Database models."""

# ruff: noqa: I001, RUF022 - Imports structured for Jinja2 template conditionals
from app.db.models.user import User
from app.db.models.session import Session
from app.db.models.conversation import Conversation, Message, ToolCall
from app.db.models.chat_file import ChatFile
from app.db.models.message_rating import MessageRating
from app.db.models.rag_document import RAGDocument
from app.db.models.sync_log import SyncLog
from app.db.models.sync_source import SyncSource
from app.db.models.conversation_share import ConversationShare
from app.db.models.user_slash_command import UserSlashCommand
from app.db.models.mcp_connection import McpConnection
from app.db.models.local_paper_library import (
    LocalPaper,
    LocalPaperChunk,
    LocalPaperFigure,
    LocalPaperLibrary,
    LocalPaperQuarantineItem,
    LocalPaperSection,
    LocalPaperSyncEvent,
    LocalPaperSyncRun,
)
from app.db.models.literature_research import (
    ResearchArtifact,
    ResearchConstraintEvaluation,
    ResearchEvidenceLocator,
    ResearchEvaluationDataset,
    ResearchEvaluationResult,
    ResearchFeedbackSample,
    ResearchFullTextAcquisition,
    ResearchMetricSnapshot,
    ResearchOutboxEvent,
    ResearchOrganization,
    ResearchOrganizationMember,
    ResearchPaperAnalysis,
    ResearchParsedBlock,
    ResearchProject,
    ResearchProjectMemory,
    ResearchProtocolVersion,
    ResearchPolicyVersion,
    ResearchRelevanceScore,
    ResearchReleaseCheck,
    ResearchRun,
    ResearchRunControl,
    ResearchSearchQuery,
    ResearchSourceFailure,
    ResearchSourcePage,
    ResearchSourceRecord,
    ResearchSynthesis,
    ResearchTaskExecution,
    ResearchVenue,
    ResearchVenueMetricFact,
    ResearchWork,
    ResearchWorkEligibility,
    ResearchWorkVersion,
    UserResearchProfile,
)

__all__ = [
    "User",
    "Session",
    "Conversation",
    "Message",
    "ToolCall",
    "ChatFile",
    "MessageRating",
    "RAGDocument",
    "SyncLog",
    "SyncSource",
    "ConversationShare",
    "UserSlashCommand",
    "McpConnection",
    "LocalPaperLibrary",
    "LocalPaper",
    "LocalPaperChunk",
    "LocalPaperSection",
    "LocalPaperFigure",
    "LocalPaperSyncRun",
    "LocalPaperSyncEvent",
    "LocalPaperQuarantineItem",
    "ResearchOutboxEvent",
    "ResearchOrganization",
    "ResearchOrganizationMember",
    "ResearchArtifact",
    "ResearchConstraintEvaluation",
    "ResearchEvidenceLocator",
    "ResearchEvaluationDataset",
    "ResearchEvaluationResult",
    "ResearchFeedbackSample",
    "ResearchFullTextAcquisition",
    "ResearchMetricSnapshot",
    "ResearchParsedBlock",
    "ResearchPaperAnalysis",
    "ResearchProject",
    "ResearchProjectMemory",
    "ResearchProtocolVersion",
    "ResearchPolicyVersion",
    "ResearchRelevanceScore",
    "ResearchReleaseCheck",
    "ResearchRun",
    "ResearchRunControl",
    "ResearchSearchQuery",
    "ResearchSourceFailure",
    "ResearchSourcePage",
    "ResearchSourceRecord",
    "ResearchSynthesis",
    "ResearchTaskExecution",
    "ResearchVenue",
    "ResearchVenueMetricFact",
    "ResearchWork",
    "ResearchWorkEligibility",
    "ResearchWorkVersion",
    "UserResearchProfile",
]
