/**
 * Fetch each catalog server's brand favicon and write them to
 * `src/lib/mcp-logos.generated.ts` as base64 data URIs.
 *
 * The demo "MCP" badge (tool-call-card) reads these so the logo renders in the
 * self-contained HTML export with no network — the badge falls back to the live
 * favicon service only for domains not baked here. Run with: bun run gen:mcp-logos
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { MCP_CATALOG } from "../src/lib/mcp-catalog";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "src", "lib", "mcp-logos.generated.ts");

/** Google's favicon service — follows redirects to the actual PNG. */
function faviconUrl(domain: string): string {
  return `https://www.google.com/s2/favicons?sz=128&domain=${encodeURIComponent(domain)}`;
}

async function fetchDataUri(domain: string): Promise<string | null> {
  try {
    const res = await fetch(faviconUrl(domain), { redirect: "follow" });
    if (!res.ok) return null;
    const type = res.headers.get("content-type") ?? "image/png";
    const b64 = Buffer.from(await res.arrayBuffer()).toString("base64");
    return `data:${type};base64,${b64}`;
  } catch {
    return null;
  }
}

const domains = [...new Set(MCP_CATALOG.map((e) => e.domain))].sort();
const logos: Record<string, string> = {};
const failed: string[] = [];
for (const domain of domains) {
  const uri = await fetchDataUri(domain);
  if (uri) {
    logos[domain] = uri;
    console.log(`  ✓ ${domain} (${Math.round(uri.length / 1024)} KB)`);
  } else {
    console.warn(`  ✗ ${domain} — skipped (fetch failed)`);
    failed.push(domain);
  }
}

const body =
  "// AUTO-GENERATED by scripts/gen-mcp-logos.ts — do not edit by hand.\n" +
  "// Brand logos for catalog MCP servers, inlined as data URIs so the \"MCP\" badge\n" +
  "// shown in demo replays / the self-contained export renders OFFLINE (no external\n" +
  "// favicon fetch). Regenerate with: bun run gen:mcp-logos\n" +
  "export const MCP_LOGOS: Record<string, string> = {\n" +
  Object.entries(logos)
    .map(([d, uri]) => `  ${JSON.stringify(d)}: ${JSON.stringify(uri)},`)
    .join("\n") +
  "\n};\n";

await writeFile(OUT, body, "utf8");
console.log(`\nWrote ${Object.keys(logos).length} logos → ${OUT}`);

if (failed.length > 0) {
  // A missing logo falls back to the live favicon service at render time, so
  // the export would quietly phone home for that badge. Fail instead of
  // shipping a half-baked file — re-run once the fetch works.
  console.error(`\n${failed.length} logo(s) missing: ${failed.join(", ")} — re-run to fix.`);
  process.exit(1);
}
